// nuxt-app/pages/blog.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { format } from 'date-fns'

const { t } = useI18n()
const config = useRuntimeConfig()

useHead({
  title: 'Blog - Farhan Fadhilah Djabari',
  meta: [
    { name: 'description', content: 'Articles and insights on mobile development, Flutter, and Kotlin.' },
  ],
})

interface BlogPost {
  title: string
  link: string
  pubDate: string
  contentSnippet: string
  categories: string[]
  readTime: number
}

const posts = ref<BlogPost[]>([])
const loading = ref(true)

onMounted(async () => {
  try {
    const data = await $fetch<BlogPost[]>(`/api/medium/posts?username=${config.public.mediumUsername}&limit=20`)
    posts.value = data
  }
  catch (error) {
    console.error('Failed to fetch blog posts:', error)
  }
  finally {
    loading.value = false
  }
})

const formatDate = (date: string) => {
  return format(new Date(date), 'MMMM dd, yyyy')
}
</script>

<template>
  <div class="min-h-screen pt-24 pb-20 px-4">
    <div class="container mx-auto max-w-5xl">
      <div class="text-center mb-12 space-y-4">
        <h1 class="text-4xl md:text-5xl font-bold">
          <span class="gradient-text">{{ t('blog.title') }} {{ t('blog.titleHighlight') }}</span>
        </h1>
        <p class="text-muted-foreground max-w-2xl mx-auto text-lg">
          {{ t('blog.subtitle') }}
        </p>
        <div class="flex items-center justify-center gap-2 text-muted-foreground">
          <span>{{ t('blog.findMeOn') }}</span>
          <a
            href="https://medium.com/@djabaridev"
            target="_blank"
            class="text-primary hover:underline font-medium"
          >
            {{ t('blog.medium') }}
          </a>
        </div>
      </div>

      <div v-if="loading" class="space-y-6">
        <Card v-for="i in 6" :key="i" class="p-6">
          <div class="animate-pulse space-y-4">
            <div class="h-6 bg-muted rounded w-3/4" />
            <div class="h-4 bg-muted rounded" />
            <div class="h-4 bg-muted rounded w-5/6" />
          </div>
        </Card>
      </div>

      <div v-else class="space-y-6">
        <Card
          v-for="post in posts"
          :key="post.link"
          class="hover-lift transition-all duration-300"
        >
          <CardHeader>
            <div class="flex items-center gap-2 text-sm text-muted-foreground mb-2">
              <Icon name="lucide:calendar" class="w-4 h-4" />
              <span>{{ formatDate(post.pubDate) }}</span>
              <span>•</span>
              <Icon name="lucide:clock" class="w-4 h-4" />
              <span>{{ post.readTime }} min read</span>
            </div>
            <CardTitle class="text-2xl hover:text-primary transition-colors">
              <a :href="post.link" target="_blank" rel="noopener noreferrer">
                {{ post.title }}
              </a>
            </CardTitle>
          </CardHeader>
          <CardContent class="space-y-4">
            <p class="text-muted-foreground">
              {{ post.contentSnippet }}
            </p>
            <div class="flex flex-wrap gap-2">
              <Badge v-for="category in post.categories" :key="category" variant="secondary">
                {{ category }}
              </Badge>
            </div>
            <Button as="a" :href="post.link" target="_blank" variant="outline" class="gap-2">
              Read More
              <Icon name="lucide:arrow-right" class="w-4 h-4" />
            </Button>
          </CardContent>
        </Card>

        <div v-if="!loading && posts.length === 0" class="text-center py-12">
          <p class="text-muted-foreground">No blog posts found.</p>
        </div>
      </div>
    </div>
  </div>
</template>

// app/blog/page.tsx
"use client"

import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { CalendarDays, Clock, ExternalLink } from "lucide-react"
import Link from "next/link"
import { useEffect, useState } from "react"
import { BlogPost } from "@/lib/model/blog-post"
import { fetchMediumPosts } from "@/lib/services/medium-api"
import { LINKS } from "@/lib/constants"

export default function BlogPage() {
  const [posts, setPosts] = useState<BlogPost[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [refreshing, setRefreshing] = useState(false)

  async function loadPosts() {
    try {
      setLoading(true)
      setError(null)

      setError(null)

      const mediumPosts = await fetchMediumPosts('djabaridev', 10)

      if (mediumPosts.length > 0) {
        setPosts(mediumPosts)
      } else {
        setPosts([])
        setError('Using cached posts')
      }
    } catch (error) {
      console.error('Failed to load Medium posts:', error)
      setPosts([])
      setError('Medium API unavailable - showing sample posts')
    } finally {
      setLoading(false)
      setRefreshing(false)
    }
  }

  useEffect(() => {
    loadPosts()
  }, [])

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    })
  }

  return (
    <div className="min-h-screen bg-background text-foreground">
      <Header />
      <main className="container mx-auto px-4 py-24">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-5xl font-bold mb-4">
              My Thoughts & <span className="text-primary">Writings</span>
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Insights, tutorials, and thoughts on mobile development, technology trends, and software engineering best
              practices.
            </p>
          </div>

          <div className="grid grid-cols-1 gap-8">
            {posts.map((post, index) => (
              <Card key={post.link || index} className="bg-card border-border hover:border-primary transition-colors">
                <CardHeader>
                  <div className="flex items-center gap-4 text-sm text-muted-foreground mb-2">
                    <div className="flex items-center gap-1">
                      <CalendarDays className="w-4 h-4" />
                      {formatDate(post.pubDate)}
                    </div>
                    <div className="flex items-center gap-1">
                      <Clock className="w-4 h-4" />
                      {post.readTime} min read
                    </div>
                  </div>
                  <CardTitle className="text-2xl hover:text-primary transition-colors">
                    <Link href={`${post.link}`} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
                      {post.title}
                      <ExternalLink className="w-5 h-5" />
                    </Link>
                  </CardTitle>
                  <CardDescription className="text-muted-foreground line-clamp-5 text-base leading-relaxed break-words overflow-hidden text-ellipsis">
                    {post.contentSnippet || post.description || 'No description available.'}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {post.categories.map((tag) => (
                      <Badge key={tag} variant="secondary" className="bg-primary/20 text-primary hover:bg-primary/30">
                        {tag}
                      </Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <div className="text-center mt-16">
            <p className="text-muted-foreground mb-4">Want to read more?</p>
            <Link
              href={LINKS.medium}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors"
            >
              Visit My Medium Profile
              <ExternalLink className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
