// nuxt-app/components/BlogSection.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { format } from 'date-fns'
import { useScrollReveal } from '~/composables/useScrollReveal'

const { t } = useI18n()
const config = useRuntimeConfig()

// Initialize scroll reveal
useScrollReveal()

interface BlogPost {
  title: string
  link: string
  pubDate: string
  contentSnippet: string
  categories: string[]
  readTime: number
}

const posts = ref<BlogPost[]>([])
const loading = ref(true)

onMounted(async () => {
  try {
    const data = await $fetch<BlogPost[]>(`/api/medium/posts?username=${config.public.mediumUsername}&limit=3`)
    posts.value = data
  }
  catch (error) {
    console.error('Failed to fetch blog posts:', error)
  }
  finally {
    loading.value = false
  }
})

const formatDate = (date: string) => {
  return format(new Date(date), 'MMM dd, yyyy')
}
</script>

<template>
  <section class="py-20 px-4 bg-muted/30">
    <div class="container mx-auto">
      <div class="text-center mb-12 space-y-4">
        <h2 class="text-3xl md:text-4xl font-bold">
          {{ t('blog.title') }} <span class="gradient-text">{{ t('blog.titleHighlight') }}</span>
        </h2>
        <p class="text-muted-foreground max-w-2xl mx-auto">
          {{ t('blog.subtitle') }}
        </p>
      </div>

      <div v-if="loading" class="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card v-for="i in 3" :key="i" class="glass-card p-6 card-shadow">
          <div class="space-y-4">
            <div class="h-6 shimmer rounded w-3/4" />
            <div class="h-4 shimmer rounded" />
            <div class="h-4 shimmer rounded w-5/6" />
          </div>
        </Card>
      </div>

      <div v-else class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <Card
          v-for="(post, index) in posts"
          :key="post.link"
          data-scroll-reveal
          class="glass-card hover-lift card-shadow transition-all duration-300 flex flex-col group border-border/50 hover:border-primary/30"
          :style="{ transitionDelay: `${index * 100}ms` }"
        >
          <CardHeader class="relative">
            <!-- Gradient overlay on hover -->
            <div class="absolute inset-0 bg-gradient-to-br from-primary/5 to-purple-500/5 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none rounded-t-xl" />

            <div class="flex items-center gap-2 text-sm text-muted-foreground mb-2 relative z-10">
              <Icon name="lucide:calendar" class="w-4 h-4" />
              <span>{{ formatDate(post.pubDate) }}</span>
              <span>•</span>
              <Icon name="lucide:clock" class="w-4 h-4" />
              <span>{{ post.readTime }} min read</span>
            </div>
            <CardTitle class="line-clamp-2 group-hover:text-primary transition-colors relative z-10">
              {{ post.title }}
            </CardTitle>
          </CardHeader>
          <CardContent class="flex-1 flex flex-col justify-between gap-4 relative z-10">
            <p class="text-muted-foreground line-clamp-3 leading-relaxed">
              {{ post.contentSnippet }}
            </p>
            <div class="flex flex-wrap gap-2">
              <Badge
                v-for="category in post.categories.slice(0, 3)"
                :key="category"
                variant="secondary"
                class="glass-card hover-scale"
              >
                {{ category }}
              </Badge>
            </div>
            <Button as="a" :href="post.link" target="_blank" variant="outline" class="w-full mt-auto gap-2 glass-button group/btn">
              Read More
              <Icon name="lucide:arrow-right" class="w-4 h-4 group-hover/btn:translate-x-1 transition-transform" />
            </Button>
          </CardContent>
        </Card>
      </div>

      <div class="text-center">
        <Button as="a" href="/blog" size="lg" class="gap-2">
          {{ t('blog.viewAll') }}
          <Icon name="lucide:arrow-right" class="w-4 h-4" />
        </Button>
      </div>
    </div>
  </section>
</template>

// components/blog-section.tsx
"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { ExternalLink, Calendar, Loader2 } from "lucide-react"
import Link from "next/link"
import { FadeInSection } from "@/components/fade-in-section"
import { useTranslation } from "@/hooks/use-translation"
import { fetchMediumPosts } from "@/lib/services/medium-api"
import { useEffect, useState } from "react"
import { LINKS } from "@/lib/constants"
import { BlogPost } from "@/lib/model/blog-post"

export function BlogSection() {
  const { t } = useTranslation()
  const [posts, setPosts] = useState<BlogPost[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  async function loadPosts() {
    try {
      setLoading(true)
      setError(null)

      const mediumPosts = await fetchMediumPosts('djabaridev', 3)

      if (mediumPosts.length > 0) {
        setPosts(mediumPosts)
      } else {
        setPosts([])
        setError('Using cached posts')
      }
    } catch (error) {
      console.error('Failed to load Medium posts:', error)
      setPosts([])
      setError('Medium API unavailable - showing sample posts')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadPosts()
  }, [])

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    })
  }

  if (loading) {
    return (
      <section className="py-24 px-4 bg-muted/30 relative overflow-hidden">
        <div className="container mx-auto max-w-6xl relative z-10">
          <div className="text-center">
            <Loader2 className="w-8 h-8 animate-spin mx-auto mb-4 text-primary" />
            <p className="text-muted-foreground">Loading latest blog posts...</p>
          </div>
        </div>
      </section>
    )
  }

  return (
    <section className="py-24 px-4 bg-muted/30 relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute inset-0">
        <div className="absolute top-20 left-10 w-32 h-32 bg-primary/10 rounded-full blur-2xl animate-pulse" />
        <div
          className="absolute bottom-20 right-10 w-48 h-48 bg-primary/5 rounded-full blur-3xl animate-pulse"
          style={{ animationDelay: "3s" }}
        />
      </div>

      <div className="container mx-auto max-w-6xl relative z-10">
        <FadeInSection>
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              {t("blog.title")} <span className="text-primary">{t("blog.titleHighlight")}</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">{t("blog.subtitle")}</p>
          </div>
        </FadeInSection>

        <div className="grid md:grid-cols-3 gap-8 mb-12">
          {posts.map((post, index) => (
            <FadeInSection key={post.link || index} delay={index * 200}>
              <Card className="bg-card border-border hover:border-primary transition-all duration-500 hover:shadow-lg group hover:scale-105">
                <CardHeader>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground mb-2">
                    <Calendar className="w-4 h-4" />
                    {formatDate(post.pubDate)}
                  </div>
                  <CardTitle className="text-xl text-foreground leading-tight group-hover:text-primary transition-colors duration-300 line-clamp-2">
                    {post.title}
                  </CardTitle>
                  <CardDescription className="text-muted-foreground line-clamp-3">
                    {post.contentSnippet || post.description || 'No description available.'}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {post.categories.slice(0, 3).map((tag, tagIndex) => (
                      <Badge
                        key={tag}
                        variant="secondary"
                        className="bg-primary/20 text-primary text-xs transition-all duration-300 hover:scale-105"
                        style={{ animationDelay: `${tagIndex * 100}ms` }}
                      >
                        {tag}
                      </Badge>
                    ))}
                    {post.categories.length > 3 && (
                      <Badge
                        variant="secondary"
                        className="bg-primary/20 text-primary text-xs transition-all duration-300 hover:scale-105"
                      >
                        +{post.categories.length - 3} more
                      </Badge>
                    )}
                  </div>
                </CardContent>
                {post.link !== "#" && (
                  <Button
                    asChild
                    size="lg"
                    variant="ghost"
                    className="w-full transition-all duration-300 hover:scale-100 rounded-b-lg rounded-t-none flex items-center justify-center"
                  >
                    <Link href={post.link} target="_blank">
                      Read More
                      <ExternalLink className="w-4 h-4 ml-2" />
                    </Link>
                  </Button>
                )}
              </Card>
            </FadeInSection>
          ))}
        </div>

        <FadeInSection delay={600}>
          <div className="text-center space-y-6">
            <Button
              asChild
              size="lg"
              className="bg-primary hover:bg-primary/90 transition-all duration-300 hover:scale-105 hover:shadow-lg"
            >
              <Link href="/blog">
                {t("blog.viewAll")}
                <ExternalLink className="w-4 h-4 ml-2" />
              </Link>
            </Button>
            <p className="text-muted-foreground">
              {t("blog.findMeOn")}{" "}
              <Link
                href={LINKS.medium}
                target="_blank"
                className="text-primary hover:underline transition-all duration-300 hover:scale-105 inline-block"
              >
                {t("blog.medium")}
              </Link>
            </p>
          </div>
        </FadeInSection>
      </div>
    </section>
  )
}
