// nuxt-app/components/ContactSection.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { LINKS } from '~/utils/constants'

const { t } = useI18n()

const contactMethods = [
  {
    icon: 'lucide:mail',
    label: t('contact.email'),
    value: 'farhanf@djabari-dev.my.id',
    href: LINKS.email,
  },
  {
    icon: 'lucide:github',
    label: t('contact.github'),
    value: 'farhanfdjabari',
    href: LINKS.github,
  },
  {
    icon: 'lucide:linkedin',
    label: t('contact.linkedin'),
    value: 'Farhan Fadhilah Djabari',
    href: LINKS.linkedin,
  },
]
</script>

<template>
  <section id="contact" class="py-20 px-4">
    <div class="container mx-auto max-w-4xl">
      <div class="text-center mb-12 space-y-4">
        <h2 class="text-3xl md:text-4xl font-bold">
          {{ t('contact.title') }} <span class="gradient-text">{{ t('contact.titleHighlight') }}</span>
        </h2>
        <p class="text-muted-foreground max-w-2xl mx-auto">
          {{ t('contact.subtitle') }}
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card
          v-for="(method, index) in contactMethods"
          :key="method.label"
          data-scroll-reveal
          class="glass-card hover-lift card-shadow transition-all duration-300 text-center group border-border/50 hover:border-primary/30"
          :style="{ transitionDelay: `${index * 100}ms` }"
        >
          <CardContent class="pt-6 space-y-4">
            <div class="w-14 h-14 rounded-full bg-gradient-to-br from-primary/20 to-purple-500/20 flex items-center justify-center mx-auto group-hover:scale-110 transition-transform">
              <Icon :name="method.icon" class="w-7 h-7 text-primary" />
            </div>
            <div class="space-y-2">
              <h3 class="font-semibold group-hover:text-primary transition-colors">
                {{ method.label }}
              </h3>
              <p class="text-sm text-muted-foreground break-all">
                {{ method.value }}
              </p>
            </div>
            <Button as="a" :href="method.href" target="_blank" variant="outline" class="w-full gap-2 glass-button group/btn">
              <Icon name="lucide:external-link" class="w-4 h-4 group-hover/btn:rotate-45 transition-transform" />
              Connect
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  </section>
</template>

// components/contact-section.tsx
"use client"

import type React from "react"
import { useState } from "react"
import { File, FileText, Github, Linkedin, Mail } from "lucide-react"
import Link from "next/link"
import { FadeInSection } from "@/components/fade-in-section"
import { useTranslation } from "@/hooks/use-translation"
import { LINKS } from "@/lib/constants"

export function ContactSection() {
  const { t } = useTranslation()

  const handleDownloadResume = () => {
    window.open(LINKS.resume, "_blank")
  }

  const contactInfo = [
    {
      icon: Mail,
      labelKey: "contact.email",
      value: "farhanf@djabari-dev.my.id",
      href: LINKS.email,
    },
    {
      icon: Github,
      labelKey: "contact.github",
      value: "FarhanFDjabari",
      href: LINKS.github,
    },
    {
      icon: Linkedin,
      labelKey: "contact.linkedin",
      value: "Farhan Fadhilah Djabari",
      href: LINKS.linkedin,
    },
  ]

  return (
    <section id="contact" className="py-24 px-4 relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute inset-0">
        <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-primary/5 rounded-full blur-3xl animate-pulse" />
        <div
          className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-primary/3 rounded-full blur-3xl animate-pulse"
          style={{ animationDelay: "2s" }}
        />
      </div>

      <div className="container mx-auto max-w-4xl relative z-10">
        <FadeInSection>
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              {t("contact.title")} <span className="text-primary">{t("contact.titleHighlight")}</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">{t("contact.subtitle")}</p>
          </div>
        </FadeInSection>

        <div className="grid lg:grid-cols-1 gap-12">
          {/* Contact Information */}
          <FadeInSection delay={400}>
            <div className="space-y-8">
              <div>
                <h3 className="text-2xl font-bold text-foreground mb-6">{t("contact.connect.title")}</h3>
              </div>

              <div className="space-y-4">
                {contactInfo.map((contact, index) => (
                  <div
                    key={contact.labelKey}
                    className="flex items-center gap-4 p-4 bg-card rounded-lg border border-border hover:border-primary transition-all duration-300 hover:scale-105 group"
                    style={{ animationDelay: `${index * 100}ms` }}
                  >
                    <contact.icon className="w-6 h-6 text-primary group-hover:scale-110 transition-transform duration-300" />
                    <div>
                      <p className="text-sm text-muted-foreground">{t(contact.labelKey as any)}</p>
                      <Link
                        href={contact.href}
                        target={contact.href.startsWith("http") ? "_blank" : undefined}
                        className="text-foreground hover:text-primary transition-colors duration-300"
                      >
                        {contact.value}
                      </Link>
                    </div>
                  </div>
                ))}
                <div
                  key="Download Resume"
                  className="flex items-center gap-4 p-4 bg-card rounded-lg border border-border hover:border-primary transition-all duration-300 hover:scale-105 group"
                  style={{ animationDelay: `${contactInfo.length * 100}ms` }}
                >
                  <FileText className="w-6 h-6 text-primary group-hover:scale-110 transition-transform duration-300" />
                  <div>
                    <p className="text-sm text-muted-foreground">Resume/CV</p>
                    <Link
                      onClick={handleDownloadResume}
                      href={LINKS.resume}
                      target="undefined"
                      className="text-foreground hover:text-primary transition-colors duration-300"
                    >
                      {t("hero.downloadResume")}
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </FadeInSection>
        </div>
      </div>
    </section>
  )
}
