// nuxt-app/components/ProjectsSection.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useScrollReveal } from '~/composables/useScrollReveal'

const { t } = useI18n()
const config = useRuntimeConfig()

// Initialize scroll reveal
useScrollReveal()

interface Repository {
  title: string
  description: string
  technologies: string[]
  githubUrl: string
  liveUrl: string | null
  stars: number
  forks: number
}

const repositories = ref<Repository[]>([])
const loading = ref(true)

onMounted(async () => {
  try {
    const data = await $fetch<Repository[]>(`/api/github/repositories?username=${config.public.githubUsername}`)
    repositories.value = data
  }
  catch (error) {
    console.error('Failed to fetch repositories:', error)
  }
  finally {
    loading.value = false
  }
})
</script>

<template>
  <section id="projects" class="py-20 px-4">
    <div class="container mx-auto">
      <div class="text-center mb-12 space-y-4">
        <h2 class="text-3xl md:text-4xl font-bold">
          {{ t('projects.title') }} <span class="gradient-text">{{ t('projects.titleHighlight') }}</span>
        </h2>
        <p class="text-muted-foreground max-w-2xl mx-auto">
          {{ t('projects.subtitle') }}
        </p>
      </div>

      <div v-if="loading" class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card v-for="i in 4" :key="i" class="glass-card p-6 card-shadow">
          <div class="space-y-4">
            <div class="h-6 shimmer rounded w-3/4" />
            <div class="h-4 shimmer rounded" />
            <div class="h-4 shimmer rounded w-5/6" />
          </div>
        </Card>
      </div>

      <div v-else class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card
          v-for="(repo, index) in repositories"
          :key="repo.githubUrl"
          data-scroll-reveal
          class="glass-card hover-lift card-shadow transition-all duration-300 overflow-hidden group border-border/50 hover:border-primary/30"
          :style="{ transitionDelay: `${index * 100}ms` }"
        >
          <CardHeader class="relative">
            <!-- Gradient overlay on hover -->
            <div class="absolute inset-0 bg-gradient-to-br from-primary/5 to-purple-500/5 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none" />

            <CardTitle class="flex items-start justify-between gap-2 relative z-10">
              <span class="group-hover:text-primary transition-colors">{{ repo.title }}</span>
              <div class="flex gap-2 text-sm text-muted-foreground">
                <span class="flex items-center gap-1 hover-scale">
                  <Icon name="lucide:star" class="w-4 h-4 text-yellow-500" />
                  {{ repo.stars }}
                </span>
                <span class="flex items-center gap-1 hover-scale">
                  <Icon name="lucide:git-fork" class="w-4 h-4 text-blue-500" />
                  {{ repo.forks }}
                </span>
              </div>
            </CardTitle>
          </CardHeader>
          <CardContent class="space-y-4 relative z-10">
            <p class="text-muted-foreground leading-relaxed">
              {{ repo.description }}
            </p>
            <div class="flex flex-wrap gap-2">
              <Badge
                v-for="tech in repo.technologies.slice(0, 5)"
                :key="tech"
                variant="secondary"
                class="hover-scale glass-card"
              >
                {{ tech }}
              </Badge>
              <Badge
                v-if="repo.technologies.length > 5"
                variant="secondary"
                class="glass-card"
              >
                +{{ repo.technologies.length - 5 }}
              </Badge>
            </div>
            <div class="flex gap-2 pt-2">
              <Button
                as="a"
                :href="repo.githubUrl"
                target="_blank"
                variant="outline"
                size="sm"
                class="gap-2 glass-button group/btn"
              >
                <Icon name="lucide:github" class="w-4 h-4 group-hover/btn:scale-110 transition-transform" />
                {{ t('projects.github') }}
              </Button>
              <Button
                v-if="repo.liveUrl"
                as="a"
                :href="repo.liveUrl"
                target="_blank"
                size="sm"
                class="gap-2 group/btn hover:shadow-lg hover:shadow-primary/25"
              >
                <Icon name="lucide:external-link" class="w-4 h-4 group-hover/btn:rotate-45 transition-transform" />
                {{ t('projects.liveDemo') }}
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  </section>
</template>

// components/projects-section.tsx
"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Github, ExternalLink, Loader2, Star, GitFork } from "lucide-react"
import Link from "next/link"
import { FadeInSection } from "@/components/fade-in-section"
import { useTranslation } from "@/hooks/use-translation"
import { LINKS } from "@/lib/constants"
import { useEffect, useState } from "react"
import { fetchPinnedRepositories } from "@/lib/services/github-api"

interface Project {
  title: string
  description: string
  technologies: string[]
  githubUrl: string
  liveUrl: string | null
  stars: number
  forks: number
}

export function ProjectsSection() {
  const { t } = useTranslation()
  const [projects, setProjects] = useState<Project[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    async function loadProjects() {
      try {
        setLoading(true)
        setError(null)
        const githubProjects = await fetchPinnedRepositories('farhanfdjabari')
        
        if (githubProjects.length > 0) {
          setProjects(githubProjects)
        } else {
          setProjects([])
          setError('No pinned projects found')
        }
      } catch (error) {
        console.error('Failed to load projects:', error)
        setProjects([])
        setError('Failed to load GitHub data')
      } finally {
        setLoading(false)
      }
    }
    loadProjects()
  }, [])

  if (loading) {
    return (
      <section id="projects" className="py-24 px-4 relative overflow-hidden">
        <div className="container mx-auto max-w-6xl relative z-10">
          <div className="text-center">
            <Loader2 className="w-8 h-8 animate-spin mx-auto mb-4 text-primary" />
            <p className="text-muted-foreground">Loading projects from GitHub...</p>
          </div>
        </div>
      </section>
    )
  }

  return (
    <section id="projects" className="py-24 px-4 relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-primary/5 to-transparent" />

      <div className="container mx-auto max-w-6xl relative z-10">
        <FadeInSection>
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              {t("projects.title")} <span className="text-primary">{t("projects.titleHighlight")}</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">{t("projects.subtitle")}</p>
          </div>
        </FadeInSection>

        <div className="grid md:grid-cols-2 gap-8">
          {projects.map((project, index) => (
            <FadeInSection key={index} delay={index * 200}>
              <Card className="bg-card border-border hover:border-primary transition-all duration-500 hover:shadow-xl hover:shadow-primary/10 group hover:scale-105">
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <CardTitle className="text-2xl text-foreground mb-2 group-hover:text-primary transition-colors duration-300">
                        {project.title}
                      </CardTitle>
                      <CardDescription className="text-muted-foreground text-base leading-relaxed">
                        {project.description}
                      </CardDescription>
                    </div>
                    {(project.stars > 0 || project.forks > 0) && (
                      <div className="flex items-center gap-3 text-sm text-muted-foreground ml-4">
                        {project.stars > 0 && (
                          <div className="flex items-center gap-1">
                            <Star className="w-4 h-4" />
                            <span>{project.stars}</span>
                          </div>
                        )}
                        {project.forks > 0 && (
                          <div className="flex items-center gap-1">
                            <GitFork className="w-4 h-4" />
                            <span>{project.forks}</span>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex flex-wrap gap-2">
                    {project.technologies.slice(0,4).map((tech, techIndex) => (
                      <Badge
                        key={tech}
                        variant="secondary"
                        className="bg-primary/20 text-primary hover:bg-primary/30 transition-all duration-300 hover:scale-105"
                        style={{ animationDelay: `${techIndex * 100}ms` }}
                      >
                        {tech}
                      </Badge>
                    ))}
                    {project.technologies.length > 4 && (
                      <Badge
                        variant="secondary"
                        className="bg-primary/20 text-primary hover:bg-primary/30 transition-all duration-300 hover:scale-105"
                      >
                        +{project.technologies.length - 4} more
                      </Badge>
                    )}
                  </div>
                  <div className="flex gap-3 pt-2">
                    <Button
                      asChild
                      size="sm"
                      className="bg-primary hover:bg-primary/90 transition-all duration-300 hover:scale-105"
                    >
                      <Link href={project.githubUrl} target="_blank">
                        <Github className="w-4 h-4 mr-2" />
                        {t("projects.github")}
                      </Link>
                    </Button>
                    {project.liveUrl && (
                      <Button
                        asChild
                        variant="outline"
                        size="sm"
                        className="border-border text-muted-foreground hover:bg-muted bg-transparent transition-all duration-300 hover:scale-105"
                      >
                        <Link href={project.liveUrl} target="_blank">
                          <ExternalLink className="w-4 h-4 mr-2" />
                          {t("projects.liveDemo")}
                        </Link>
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>
            </FadeInSection>
          ))}
        </div>
      </div>
    </section>
  )
}
